apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c70o4ada0-python 
  janus-idp.io/tekton: c70o4ada0-python
  backstage.io/kubernetes-id: c70o4ada0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c70o4ada0-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml